/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  bittensorSidebar: [
    // 	{
    // 	type: 'link',
    // 	href: 'https://docs.learnbittensor.org',
    // 	label: "Search",
    // 	className: 'sidebarSearch', //  based on Class name it will add search component
    // },
    "index",
    {
      type: "category",
      label: "Releases and Announcements",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "resources/bittensor-rel-notes",
          label: "Releases",
        },
        {
          type: "doc",
          id: "learn/announcements",
          label: "Announcements",
        },
      ],
    },
    {
      type: "category",
      label: "Understand Bittensor",
      collapsible: true,
      collapsed: true,
      items: [
        "learn/introduction",
        "resources/questions-and-answers",
        "subnets/understanding-subnets",
        "learn/anatomy-of-incentive-mechanism",
        "subnets/understanding-multiple-mech-subnets",
        "learn/neurons",
        "learn/emissions",
        "learn/ema",
        "learn/yuma-consensus",
        "learn/yc3-blog",
        "concepts/weight-copying-in-bittensor",
        "learn/yuma3-migration-guide",
        "learn/fees",
        "learn/chain-rate-limits",
        {
          type: "category",
          label: "Navigating Subtensor Codebase",
          link: { type: "doc", id: "navigating-subtensor/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "navigating-subtensor/emissions-coinbase",
            "navigating-subtensor/epoch",
            "navigating-subtensor/swap-stake",
          ],
        },
        "resources/community-links",
      ],
    },
    {
      type: "category",
      label: "Wallets and Keys",
      collapsible: true,
      collapsed: true,
      items: [
        "keys/wallets",
        "keys/working-with-keys",
        "keys/handle-seed-phrase",
        "keys/coldkey-hotkey-security",
        "keys/address-poisoning-scams",
        {
          type: "category",
          label: "Proxies",
          collapsible: true,
          collapsed: true,
          items: [
            "keys/proxies/index",
            "keys/proxies/working-with-proxies",
            "keys/proxies/pure-proxies",
          ],
        },
        "keys/multisig",
        "keys/schedule-coldkey-swap",
      ],
    },

    {
      type: "category",
      label: "Staking/Delegation",
      collapsible: true,
      collapsed: true,
      items: [
        "staking-and-delegation/delegation",
        "staking-and-delegation/stakers-btcli-guide",
        "staking-and-delegation/managing-stake-btcli",
        "staking-and-delegation/managing-stake-sdk",
        "keys/proxies/staking-with-proxy",
        {
          type: "category",
          label: "Root claims",
          collapsible: true,
          collapsed: true,
          items: [
            "staking-and-delegation/root-claims/index",
            "staking-and-delegation/root-claims/managing-root-claims",
          ],
        },
        "learn/price-protection",
        "learn/slippage",
        "staking-and-delegation/staking-polkadot-js",
        "staking-and-delegation/using-ledger-hw-wallet",
      ],
    },
    {
      type: "category",
      label: "Mining",
      collapsible: true,
      collapsed: true,
      items: [
        "miners/index",
        "miners/miners-btcli-guide",
        "miners/autostaking",
      ],
    },

    {
      type: "category",
      label: "Validating",
      collapsible: true,
      collapsed: true,
      items: [
        "validators/index",
        "validators/child-hotkeys",
        "validators/validators-btcli-guide",
      ],
    },
    {
      type: "category",
      label: "Liquidity Positions (Uniswap)",
      collapsible: true,
      collapsed: true,
      items: [
        "liquidity-positions/liquidity-positions",
        "liquidity-positions/managing-liquidity-positions",
      ],
    },
    {
      type: "category",
      label: "Managing Subnets",
      collapsible: true,
      collapsed: true,
      items: [
        "subnets/metagraph",
        "subnets/create-a-subnet",
        {
          type: "category",
          label: "Crowdloans",
          collapsible: true,
          collapsed: true,
          link: { type: "doc", id: "subnets/crowdloans/index" },
          items: ["subnets/crowdloans/crowdloans-tutorial"],
        },
        "subnets/subnet-creators-btcli-guide",
        "subnets/subnet-hyperparameters",
        "subnets/working-with-subnets",
        "subnets/managing-mechanisms-with-sdk",
        "subnets/managing-mechanisms-btcli",
        "subnets/uid-trimming",
        "subnets/subnet-deregistration",
        "subnets/walkthrough-prompting",
        "tutorials/basic-subnet-tutorials",
        "tutorials/ocr-subnet-tutorial",
      ],
    },
    {
      type: "category",
      label: "BTCLI: The Bittensor CLI",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "btcli/overview" },
      items: [
        "getting-started/install-btcli",
        "btcli/btcli-permissions",
        "btcli/btcli",
      ],
    },
    {
      type: "category",
      label: "Bittensor Python SDK",
      collapsible: true,
      collapsed: true,
      items: [
        "sdk/index",
        "getting-started/installation",
        "sdk/env-vars",
        "sdk/bt-api-ref",
        "sdk/subtensor-api",
        "sdk/mev-protection",
        "getting-started/install-wallet-sdk",
        "sdk/call",
        "sdk/migration-guide",
        "subnets/asyncio",
        "sdk/managing-subtensor-connections",
      ],
    },

    {
      type: "category",
      label: "Tools and Special Features",
      link: { type: "doc", id: "concepts/tools" },
      collapsible: true,
      collapsed: true,
      items: [
        "concepts/bittensor-networks",
        "concepts/halving",
        "concepts/mev-shield/index",
        "concepts/commit-reveal",
        "concepts/consensus-based-weights",
        "concepts/bt-logging-levels",
        "resources/utilities",
      ],
    },

    {
      type: "category",
      label: "Local Development",
      collapsible: true,
      collapsed: true,
      items: [
        "local-build/deploy",
        "local-build/provision-wallets",
        "local-build/create-subnet",
        "local-build/mine-validate",
      ],
    },

    {
      type: "category",
      label: "Subtensor Nodes",
      link: { type: "doc", id: "subtensor-nodes/index" },
      collapsible: true,
      collapsed: true,
      items: [
        "subtensor-nodes/subtensor-node-requirements",
        "subtensor-nodes/using-source",
        "subtensor-nodes/using-docker",
        "subtensor-nodes/subtensor-storage-query-examples",
      ],
    },

    {
      type: "category",
      label: "Bittensor EVM",
      items: [
        "evm-tutorials/index",
        "evm-tutorials/subtensor-networks",
        "evm-tutorials/bridge-vtao",
        "evm-tutorials/evm-testnet-with-metamask-wallet",
        "evm-tutorials/evm-localnet-with-metamask-wallet",
        "evm-tutorials/evm-mainnet-with-metamask-wallet",
        "evm-tutorials/hardhat-config-for-subtensor-evm",
        "evm-tutorials/remix-config-for-subtensor-evm",
        "evm-tutorials/troubleshooting",
      ],
    },
    {
      type: "category",
      link: { type: "doc", id: "evm-tutorials/examples" },
      label: "Bittensor EVM: Examples and Precompiles",
      items: [
        "evm-tutorials/convert-h160-to-ss58",
        "evm-tutorials/transfer-from-metamask-to-ss58",
        "evm-tutorials/transfer-between-two-h160-accounts",
        "evm-tutorials/vtao-bridge-tutorial",
        "evm-tutorials/vtao-liquidity-on-aerodrome",
        "evm-tutorials/withdraw-from-alice",
        "evm-tutorials/ed25519-verify-precompile",
        "evm-tutorials/staking-precompile",
        "evm-tutorials/subnet-precompile",
        "evm-tutorials/metagraph-precompile",
        "evm-tutorials/neuron-precompile",
      ],
    },
    // {
    //   type: "category",
    //   label: "Bittensor EVM Smart Contracts",
    //   link: {type: "doc", id: "evm-tutorials/index",},
    //   collapsible: true,
    //   collapsed: true,
    //   items: [
    //     "evm-tutorials/install",
    //     ,

    //   ],
    // },
    {
      type: "category",
      label: "Governance",
      collapsible: true,
      collapsed: true,
      items: [
        "governance/governance",
        "governance/senate",
        "governance/senators-btcli-guide",
      ],
    },

    {
      type: "category",
      label: "Errors and Troubleshooting",
      collapsible: true,
      collapsed: true,
      items: [
        "errors/index",
        "errors/custom",
        "errors/subtensor",
        "errors/troubleshooting",
      ],
    },
    "resources/glossary",
    "resources/community-links",
    "resources/media-assets",
  ],
};

module.exports = sidebars;
